### ISSUE TITLE
I create a demo from based on ur document,but I get an error,

### ISSUE THREAD

**Issue by qingranfjj** [cosysoft/device#1]
public static void main(String[] args) {
		// TODO Auto-generated method stub
		TreeSet<AndroidDevice> devices = AndroidDeviceStore.getInstance()
		        .getDevices();
		AndroidDevice device = devices.pollFirst();
		System.out.println(device.getName());
		AndroidApp app = new DefaultAndroidApp(new File(
		        "/Users/fujingjing/Downloads/taobao-android.apk"));
		device.install(app);
		if (device.isInstalled(app)) {
		    device.uninstall(app);
		}
		System.out.println("finish");
	}

Exception in thread "main" java.lang.NoSuchMethodError: com.android.ddmlib.IDevice.getName()Ljava/lang/String;
	at com.github.cosysoft.device.android.impl.AndroidDeviceStore.initializeAdbConnection(AndroidDeviceStore.java:98)
	at com.github.cosysoft.device.android.impl.AndroidDeviceStore.initAndroidDevices(AndroidDeviceStore.java:52)
	at com.github.cosysoft.device.android.impl.AndroidDeviceStore$DeviceStoreHolder.init(AndroidDeviceStore.java:35)
	at com.github.cosysoft.device.android.impl.AndroidDeviceStore$DeviceStoreHolder.<clinit>(AndroidDeviceStore.java:30)
	at com.github.cosysoft.device.android.impl.AndroidDeviceStore.getInstance(AndroidDeviceStore.java:41)
	at com.alibaba.mtl.agent.script.DdmlibTest.main(DdmlibTest.java:15)

**Comment by cosyman** [comment]
Please ensure the class com.android.ddmlib.IDevice in your classpath has method getName()

If you run project with maven in eclipse, Select the pom.xml and right click ,force update to download the correct ddmlib version
